### ISSUE TITLE
I don't get it oO

### ISSUE THREAD

**Issue by MichelDiz** [karimnaaji/vectiler#23]
Well, hi there!

Very interesting project but I didn't get anything. I tried on MAC Sierra, tried on Windows. But no success.

Well, on Mac. I have to Clone the repo? couse the "vectiler-osx-x86_64.out" doesn't do nothing. Just open the App Store and nothing, just a bunch of others apps nothing to do with.

So I gonna do my tries here. Can anyone clarify my path?

Best Regards.

**Comment by MichelDiz** [comment]
I get it xD

I just have problem to understand clearly about the tiles ranges. Have the tiles to be match with the zoom value?

**Comment by karimnaaji** [comment]
Hey @MichelDiz !

Since it is a command line tool you would need to open the terminal to be able to interact with it. In the future a better UI with an app you can run and might be available.

The tile range will just generate a larger mesh, for example: requesting a tile at with an id `x` and `y` for a zoom `z` with a tile range `range_x` and `range_y` of 2 will generate a unique mesh containing the tiles `(x,y,z)`,`(x+1,y,z)`,`(x,y+1,z)`,`(x+1,y+1,z)`.

>Have the tiles to be match with the zoom value?

If you mean that the range will increase for the same zoom value, then yes.

**Comment by MichelDiz** [comment]
Right! Well I succeeded. (Can sign as solved)

But I have few problems. In mm or inches - What would be the proportion of the map? Cause I'm putting this map inside the Unreal Engine 4 to create a environment. But I'm guessing the calculation on proportions. it comes like very tiny. I think like less than 8 cm. (But It should be kilometers)

I put like 6000 times the size to get something related to reality. Using my guessing measurement. Like Google earth measures and putting BSD to compare. But is acceptable visually now.

Another thing is that it creates a lot of meshs an faces like a mess. But in the 3D Max I would be able to clean it.

Ah! I was almost forgetting! the information for creation of the tiles comes from where? Google maps it's self? or some third informations? Couse few build are missing. Importants ones. Like very important to the city that they are on the Google maps, but no sign on the meshes.

By the way, I think you could use the Electron JS project to create the UI Apps. It's use JS + Chromium project and you're able to use the same code for Windows, mac and others.

Thank you for your work and attention. Best Regards.

**Comment by MichelDiz** [comment]
About

> Have the tiles to be match with the zoom value?

Forget it, I was just confused at the time. Now I understand.

**Comment by karimnaaji** [comment]
I totally forget to respond to this issue since I only focused on your last message, really sorry about the late response.

```
But I have few problems. In mm or inches - What would be the proportion of the map? Cause I'm putting this map inside the Unreal Engine 4 to create a environment. But I'm guessing the calculation on proportions. it comes like very tiny. I think like less than 8 cm. (But It should be kilometers)
```
The proportion of the tile are always arbitrary depending on the zoom level you are at. A tile coordinate a zoom 1 will have a different size than a coordinate a zoom 2. You could find out what is the appropriate scale by knowing how much coverage a tile has at a specific zoom level. Each tile will have its coordinate reduced to 0 and 1.

```
Another thing is that it creates a lot of meshs an faces like a mess. But in the 3D Max I would be able to clean it.
```
Yes this is a known issue, the quality of the mesh will be most likely depending on the underlying vector  tile data. Some clean up pass would be beneficial.

```
Ah! I was almost forgetting! the information for creation of the tiles comes from where? Google maps it's self? or some third informations? Couse few build are missing. Importants ones. Like very important to the city that they are on the Google maps, but no sign on the meshes.
```

The data is served by the mapzen vector tile service: https://mapzen.com/documentation/vector-tiles/. Which is sourced from open street map. If some building are missing, it could also be that they are missing a `height` property. This can be solved by giving them a minimum fixed height (see the `--buildingsHeight` option).

```
By the way, I think you could use the Electron JS project to create the UI Apps. It's use JS + Chromium project and you're able to use the same code for Windows, mac and others.
```

I like the idea of Electron, and I guess that for users that wouldn't care downloading heavy sized binary executable that would work, the only thing I don't like a lot is that the app would be unnecessarily bloated. But you're right that this would give direct UI access and would surely make it nicer to use. If you are interested in this let me know.
