### ISSUE TITLE
Project usage at present

### ISSUE THREAD

**Issue by RohanGautam** [karimnaaji/vectiler#27]
Hello! Right off the bat, I'd like to say this is a really cool project. I have a few concerns and doubts regarding it's usage at present.

Poking around and running the demo CLI example, the output is as expected. I'm not however, able to get any other model of choice. For example, running
 `./vectiler.out --tilex 16811/16821 --tiley 24364/24374 --tilez 15 --terrain 1 --buildings 1 --terrainExtrusionScale 1.5 --buildingsExtrusionScale 1.9`
gives just a flat pane, with no 3d information at all.

I'm wondering if this is because of my lack of understanding of vector tile coordinates, (I've tried my best to understand it) Or because MapZen, which this project queries, has recently [shut down](https://www.mapzen.com/blog/shutdown/). 

Any help/updates regarding the above would be great, as I'm interested in using and adding onto this project. Thanks!!

**Comment by karimnaaji** [comment]
Mapzen services have transitioned to the Linux Foundation, refer https://www.mapzen.com/blog/mapzen-is-now-a-linux-foundation-project/. You can open a new API key for the tile service for free here: https://www.nextzen.org/.

The tile coordinates that you have here seem to be right down of the south atlantic ocean. That's why there is no data and it's a plane, what city or location you're trying to build? Make sure to use https://www.maptiler.com/google-maps-coordinates-tile-bounds-projection/ 'Google' coordinate system in the tiles. 

For example here the tiles would be --tilex 16597/16598 --tiley 11272/11273 --tilez 15: 

![Screen Shot 2020-01-05 at 12 11 08 PM](https://user-images.githubusercontent.com/7061573/71783416-7d3d2780-2fb4-11ea-84c7-a12605dcb332.png)


Selecting the tiles this way is cumbersome but these are the limitations of having a CLI only tool. There are a few ways the tile selection could be made simpler, by adding a very simple user interface with a search bar and display a small raster map for manual tile selection.

Let me know if you have any other questions!

**Comment by RohanGautam** [comment]
Oh I see. That clears up basically everything I asked about.
It's up and working with the existing API key too!

Thanks for the timely response ^_^ I'll close this issue!
