### ISSUE TITLE
Catch exceptions in main()?

### ISSUE THREAD

**Issue by elfring** [karimnaaji/vectiler#9]
I expect that exception handling is usually supported by a C++ program. I wonder why your function "[main](https://github.com/karimnaaji/vectiler/blob/540af77f4c57cbf7a15a9f37ddb389a5b07e1f7b/renderer/main.cpp#L22 "main() function")" does not contain [corresponding try and catch instructions](http://stackoverflow.com/questions/368184/does-it-make-sense-to-catch-exceptions-in-the-main "Does it make sense to catch exceptions in the main(…)?") so far.

How do you think about recommendations by Matthew Wilson in [an article](http://accu.org/index.php/journals/1706 "Quality Matters #6: Exceptions for Practically-Unrecoverable Conditions")?

Would you like to adjust the implementation if you consider [effects for uncaught/unhandled exceptions](http://www.informit.com/guides/content.aspx?g=cplusplus&seqNum=108 "Uncaught exceptions") like they are described by Danny Kalev?

**Comment by karimnaaji** [comment]
Hey @elfring,

Thanks for the docs. I have no thoughts about it those articles, but will give it a look.

I personally don't think C++ exceptions are a magical thing that makes your program safer once enabled, especially because of the language itself. I tend not to use C++ exceptions at all, except when the `stl` requires it for some reason.

The `main` function you pointed out is the example renderer used for debugging the result of the exporter (`located in `src/`), this renderer is still a wip and the effort is currently put on the wavefront exporter.

**Comment by elfring** [comment]
Would you like to [reconsider consequences from implementation-defined behaviour](https://stackoverflow.com/questions/5557555/raii-and-stack-unwinding "RAII and Stack unwinding")?
